SET REFERENTIAL_INTEGRITY = FALSE;
TRUNCATE TABLE passengers RESTART IDENTITY;
TRUNCATE TABLE user_authority RESTART IDENTITY;
TRUNCATE TABLE authorities RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE cruises RESTART IDENTITY;
TRUNCATE TABLE cruise_station RESTART IDENTITY;
TRUNCATE TABLE tickets RESTART IDENTITY;
TRUNCATE TABLE ships RESTART IDENTITY;
TRUNCATE TABLE staff RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY = FALSE